/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aed.hospitalmanagement;

import com.aed.backend.PatientDirectory;
import com.aed.backend.DoctorDirectory;
import com.aed.backend.DoctorPerson;
import com.aed.backend.Encounter;
import com.aed.backend.EncounterHistory;
import com.aed.backend.Person;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tarush
 */
public class hospitalManagement extends javax.swing.JFrame {
    String genderString = "Unknown";
    PatientDirectory dir = new PatientDirectory();
    DoctorDirectory docDir = new DoctorDirectory();
    EncounterHistory encHistory = new EncounterHistory();
    Encounter encToWorkWith = new Encounter();
    

    /**
     * Creates new form hospitalManagement
     */
    public hospitalManagement() {
        initComponents();
        medicalLicenseNumberTextField.setEnabled(false);
        userName.setEnabled(false);
        encounterID.setEnabled(false);
        patientAgeFieldVitalSignsRecording.setEnabled(false);
        bloodGroupFieldVitalSignsRecording.setEnabled(false);
        jTextArea4.setEnabled(false);
    }
    
    public void PanelPaint(JPanel page){
        Parent.removeAll();
        Parent.add(page);
        Parent.repaint();
        Parent.revalidate();
    }
    
    public void SplitPanelPaint(JPanel page){
        RightComponent.removeAll();
        RightComponent.add(page);
        RightComponent.repaint();
        RightComponent.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        Parent = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        AppLogo = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Register = new javax.swing.JPanel();
        AppLogo1 = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        usernameTextField1 = new javax.swing.JTextField();
        password1 = new javax.swing.JLabel();
        passwordTextField1 = new javax.swing.JPasswordField();
        emailID = new javax.swing.JLabel();
        mailIDTextField = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        role = new javax.swing.JLabel();
        rolesComboBox = new javax.swing.JComboBox<>();
        gender = new javax.swing.JLabel();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        othersButton = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        DOB = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        medicalLicenseNumberTextField = new javax.swing.JTextField();
        medicalLicense = new javax.swing.JLabel();
        Workspace = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        RightComponent = new javax.swing.JPanel();
        PatientHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        createAppointment = new javax.swing.JButton();
        viewAppoitnmentPatient = new javax.swing.JButton();
        CreatePatientAppointment = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PatientAppointmentDate = new javax.swing.JLabel();
        PatientAppointmentDateChooser = new com.toedter.calendar.JDateChooser();
        PatientAppointmentSubmit = new javax.swing.JButton();
        PatientAppointmentCancel = new javax.swing.JButton();
        PatientAppointmentDoctor = new javax.swing.JLabel();
        PatientAppointmentDrList = new javax.swing.JComboBox<>();
        PatientAppointmentReason = new javax.swing.JLabel();
        PatientAppointmentReasonArea = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        ViewPatientAppointment = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PatienAppointmentHistory = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        BackToPatientHome = new javax.swing.JButton();
        ViewAppointmentUsername = new javax.swing.JLabel();
        ViewAppointmentWith = new javax.swing.JLabel();
        ViewAppointmentDate = new javax.swing.JLabel();
        HeartRate = new javax.swing.JLabel();
        ViewAppointmentAilment = new javax.swing.JLabel();
        BloodpressureViewAppointment = new javax.swing.JLabel();
        temperatureViewAppointment = new javax.swing.JLabel();
        respirationRateViewAppointment = new javax.swing.JLabel();
        DiagnosisViewAppointment = new javax.swing.JLabel();
        HeightViewAppointment = new javax.swing.JLabel();
        DoctorHome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ViewEncounterHistoryDoctor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        DoctorAppointment = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        AddVitalSigns = new javax.swing.JButton();
        PatientEncounterHistory = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PatientEncounterHistoryDoctor = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        DoctorHomeBack1 = new javax.swing.JButton();
        VitalSignsPage = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        DoctorHomeBack = new javax.swing.JButton();
        AddVitalSignsToEncounter = new javax.swing.JButton();
        ClearVitalSigns = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        encounterID = new javax.swing.JTextField();
        usernameVitalSignsRecording = new javax.swing.JLabel();
        encounterIDVitalSignsRecording = new javax.swing.JLabel();
        patientAgeFieldVitalSignsRecording = new javax.swing.JTextField();
        patientAgeVitalSignsRecording = new javax.swing.JLabel();
        bloodGroupIDVitalSignsRecording = new javax.swing.JLabel();
        bloodGroupFieldVitalSignsRecording = new javax.swing.JTextField();
        heightVitalSignsRecording1 = new javax.swing.JLabel();
        bloodPressureIDVitalSignsRecording = new javax.swing.JLabel();
        temperatureVitalSignsRecording3 = new javax.swing.JLabel();
        respirationRateIDVitalSignsRecording4 = new javax.swing.JLabel();
        heightFieldVitalSignsRecording1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bloodPressureFieldVitalSignsRecording = new javax.swing.JTextField();
        respirationRateFieldVitalSignsRecording = new javax.swing.JTextField();
        temperatureFieldVitalSignsRecording4 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        diagnosisVitalSignsRecording1 = new javax.swing.JLabel();
        ailmentVitalSignsRecording2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        Grievences = new javax.swing.JPanel();
        MailIDGrievencesLabel = new javax.swing.JLabel();
        mailIDGrievences = new javax.swing.JTextField();
        NumberGrievencesLabel = new javax.swing.JLabel();
        NumberGrievences = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CancelGrievences = new javax.swing.JButton();
        SubmitGrievences = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Parent.setLayout(new java.awt.CardLayout());

        AppLogo.setText("AppLogo");

        username.setText("Username:");

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });

        password.setText("Password:");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Issues? Contact System Admin");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username)
                                    .addComponent(password))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordTextField)
                                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(AppLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AppLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        Parent.add(Login, "card2");

        AppLogo1.setText("AppLogo");

        username1.setText("Username:");

        password1.setText("Password:");

        passwordTextField1.setText("jPasswordField1");

        emailID.setText("Email ID:");

        phone.setText("Phone No. :");

        phoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextFieldActionPerformed(evt);
            }
        });

        role.setText("Role:");

        rolesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient", "Doctor", "System Administration" }));
        rolesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolesComboBoxActionPerformed(evt);
            }
        });

        gender.setText("Gender:");

        genderButtonGroup.add(maleButton);
        maleButton.setText("Male");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });

        genderButtonGroup.add(femaleButton);
        femaleButton.setText("Female");
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });

        genderButtonGroup.add(othersButton);
        othersButton.setText("Others");
        othersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersButtonActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        DOB.setText("Date of birth:");

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        medicalLicense.setText("Medical license No.:");

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterLayout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegisterLayout.createSequentialGroup()
                        .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(register)
                                .addComponent(medicalLicense))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(username1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AppLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addComponent(maleButton)
                        .addGap(18, 18, 18)
                        .addComponent(femaleButton)
                        .addGap(18, 18, 18)
                        .addComponent(othersButton))
                    .addComponent(rolesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicalLicenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton3)))
                .addGap(218, 218, 218))
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AppLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maleButton)
                    .addComponent(femaleButton)
                    .addComponent(othersButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicalLicenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicalLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register)
                    .addComponent(jButton3))
                .addGap(21, 21, 21))
        );

        Parent.add(Register, "card3");

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(3);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton5.setText("Log out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(512, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(45, 45, 45))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        RightComponent.setBackground(new java.awt.Color(255, 255, 255));
        RightComponent.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("Welcome Patient");

        createAppointment.setText("Create Appointment");
        createAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAppointmentActionPerformed(evt);
            }
        });

        viewAppoitnmentPatient.setText("View Appointments");
        viewAppoitnmentPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAppoitnmentPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PatientHomeLayout = new javax.swing.GroupLayout(PatientHome);
        PatientHome.setLayout(PatientHomeLayout);
        PatientHomeLayout.setHorizontalGroup(
            PatientHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientHomeLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(PatientHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PatientHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(viewAppoitnmentPatient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createAppointment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        PatientHomeLayout.setVerticalGroup(
            PatientHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createAppointment)
                .addGap(26, 26, 26)
                .addComponent(viewAppoitnmentPatient)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        RightComponent.add(PatientHome, "card2");

        CreatePatientAppointment.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        jLabel2.setText("Create appointment");

        PatientAppointmentDate.setText("Date of appointment:");

        PatientAppointmentSubmit.setBackground(new java.awt.Color(51, 153, 255));
        PatientAppointmentSubmit.setText("Submit");
        PatientAppointmentSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientAppointmentSubmitActionPerformed(evt);
            }
        });

        PatientAppointmentCancel.setBackground(new java.awt.Color(255, 51, 51));
        PatientAppointmentCancel.setText("Cancel");
        PatientAppointmentCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientAppointmentCancelActionPerformed(evt);
            }
        });

        PatientAppointmentDoctor.setText("Appointment with:");

        PatientAppointmentDrList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Selected" }));

        PatientAppointmentReason.setText("Ailment:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        PatientAppointmentReasonArea.setViewportView(jTextArea2);

        javax.swing.GroupLayout CreatePatientAppointmentLayout = new javax.swing.GroupLayout(CreatePatientAppointment);
        CreatePatientAppointment.setLayout(CreatePatientAppointmentLayout);
        CreatePatientAppointmentLayout.setHorizontalGroup(
            CreatePatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
            .addGroup(CreatePatientAppointmentLayout.createSequentialGroup()
                .addGroup(CreatePatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreatePatientAppointmentLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreatePatientAppointmentLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(CreatePatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PatientAppointmentDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientAppointmentReason, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CreatePatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PatientAppointmentDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PatientAppointmentDrList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PatientAppointmentReasonArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatePatientAppointmentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PatientAppointmentCancel)
                .addGap(18, 18, 18)
                .addComponent(PatientAppointmentSubmit)
                .addGap(27, 27, 27))
        );
        CreatePatientAppointmentLayout.setVerticalGroup(
            CreatePatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePatientAppointmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(CreatePatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PatientAppointmentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PatientAppointmentDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(CreatePatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientAppointmentDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PatientAppointmentDrList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreatePatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreatePatientAppointmentLayout.createSequentialGroup()
                        .addComponent(PatientAppointmentReason, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(330, 330, 330))
                    .addGroup(CreatePatientAppointmentLayout.createSequentialGroup()
                        .addComponent(PatientAppointmentReasonArea, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CreatePatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientAppointmentSubmit)
                            .addComponent(PatientAppointmentCancel))
                        .addGap(58, 58, 58))))
        );

        RightComponent.add(CreatePatientAppointment, "card3");

        PatienAppointmentHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Encounter ID", "Appointment with", "Appointment date", "Ailment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PatienAppointmentHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatienAppointmentHistoryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(PatienAppointmentHistory);
        if (PatienAppointmentHistory.getColumnModel().getColumnCount() > 0) {
            PatienAppointmentHistory.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        jLabel3.setText("View Appointments");

        BackToPatientHome.setText("Back");
        BackToPatientHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToPatientHomeActionPerformed(evt);
            }
        });

        ViewAppointmentUsername.setText("Username:");

        ViewAppointmentWith.setText("Appointment with:");

        ViewAppointmentDate.setText("Date:");

        HeartRate.setText("Heart Rate:");

        ViewAppointmentAilment.setText("Ailment:");

        BloodpressureViewAppointment.setText("Blood Pressure:");

        temperatureViewAppointment.setText("Temperature:");

        respirationRateViewAppointment.setText("Respiration Rate:");

        DiagnosisViewAppointment.setText("Diagnosis:");

        HeightViewAppointment.setText("Height:");

        javax.swing.GroupLayout ViewPatientAppointmentLayout = new javax.swing.GroupLayout(ViewPatientAppointment);
        ViewPatientAppointment.setLayout(ViewPatientAppointmentLayout);
        ViewPatientAppointmentLayout.setHorizontalGroup(
            ViewPatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
            .addGroup(ViewPatientAppointmentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewPatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewPatientAppointmentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BackToPatientHome))
                    .addGroup(ViewPatientAppointmentLayout.createSequentialGroup()
                        .addGroup(ViewPatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewPatientAppointmentLayout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ViewAppointmentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewPatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ViewAppointmentDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewAppointmentWith, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                            .addComponent(ViewAppointmentAilment, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiagnosisViewAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewPatientAppointmentLayout.createSequentialGroup()
                                .addComponent(HeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BloodpressureViewAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(temperatureViewAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(respirationRateViewAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(HeightViewAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ViewPatientAppointmentLayout.setVerticalGroup(
            ViewPatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewPatientAppointmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewAppointmentUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewAppointmentWith)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewAppointmentDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewPatientAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HeartRate)
                    .addComponent(BloodpressureViewAppointment)
                    .addComponent(temperatureViewAppointment)
                    .addComponent(respirationRateViewAppointment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(HeightViewAppointment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewAppointmentAilment)
                .addGap(12, 12, 12)
                .addComponent(DiagnosisViewAppointment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackToPatientHome)
                .addGap(12, 12, 12))
        );

        RightComponent.add(ViewPatientAppointment, "card4");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("Welcome Doctor");

        ViewEncounterHistoryDoctor.setText("View Encounter history");
        ViewEncounterHistoryDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEncounterHistoryDoctorActionPerformed(evt);
            }
        });

        DoctorAppointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appointment ID", "Patient Name", "Appointment date", "Ailment"
            }
        ));
        jScrollPane3.setViewportView(DoctorAppointment);

        jLabel5.setText("Appointments list");

        AddVitalSigns.setText("Add Vital Signs");
        AddVitalSigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVitalSignsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DoctorHomeLayout = new javax.swing.GroupLayout(DoctorHome);
        DoctorHome.setLayout(DoctorHomeLayout);
        DoctorHomeLayout.setHorizontalGroup(
            DoctorHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorHomeLayout.createSequentialGroup()
                .addGroup(DoctorHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addGroup(DoctorHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DoctorHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorHomeLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(AddVitalSigns)
                                .addGap(18, 18, 18)
                                .addComponent(ViewEncounterHistoryDoctor))
                            .addGroup(DoctorHomeLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(DoctorHomeLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DoctorHomeLayout.setVerticalGroup(
            DoctorHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorHomeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(DoctorHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewEncounterHistoryDoctor)
                    .addComponent(AddVitalSigns))
                .addGap(36, 36, 36))
        );

        RightComponent.add(DoctorHome, "card5");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setText("Encounter History");

        PatientEncounterHistoryDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Age", "Gender", "Ailments", "Diagnosis", "Encounter Date"
            }
        ));
        jScrollPane4.setViewportView(PatientEncounterHistoryDoctor);

        jLabel8.setText("Show Vital signs and other details here");

        DoctorHomeBack1.setText("Back");
        DoctorHomeBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorHomeBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PatientEncounterHistoryLayout = new javax.swing.GroupLayout(PatientEncounterHistory);
        PatientEncounterHistory.setLayout(PatientEncounterHistoryLayout);
        PatientEncounterHistoryLayout.setHorizontalGroup(
            PatientEncounterHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientEncounterHistoryLayout.createSequentialGroup()
                .addGroup(PatientEncounterHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientEncounterHistoryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
                    .addGroup(PatientEncounterHistoryLayout.createSequentialGroup()
                        .addGroup(PatientEncounterHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PatientEncounterHistoryLayout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PatientEncounterHistoryLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatientEncounterHistoryLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DoctorHomeBack1)))
                .addContainerGap())
        );
        PatientEncounterHistoryLayout.setVerticalGroup(
            PatientEncounterHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientEncounterHistoryLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(180, 180, 180)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DoctorHomeBack1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        RightComponent.add(PatientEncounterHistory, "card6");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel7.setText("Vital Signs Recording");

        DoctorHomeBack.setText("Back");
        DoctorHomeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorHomeBackActionPerformed(evt);
            }
        });

        AddVitalSignsToEncounter.setText("Add Vital Signs");
        AddVitalSignsToEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVitalSignsToEncounterActionPerformed(evt);
            }
        });

        ClearVitalSigns.setText("Clear");

        usernameVitalSignsRecording.setText("Username:");

        encounterIDVitalSignsRecording.setText("Encounter ID:");

        patientAgeVitalSignsRecording.setText("Age:");

        bloodGroupIDVitalSignsRecording.setText("Blood group:");

        heightVitalSignsRecording1.setText("Height:");

        bloodPressureIDVitalSignsRecording.setText("Blood pressure:");

        temperatureVitalSignsRecording3.setText("Temperature:");

        respirationRateIDVitalSignsRecording4.setText("Respiration rate:");

        jLabel9.setText("cm");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        diagnosisVitalSignsRecording1.setText("Diagnosis:");

        ailmentVitalSignsRecording2.setText("Ailment:");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane6.setViewportView(jTextArea4);

        javax.swing.GroupLayout VitalSignsPageLayout = new javax.swing.GroupLayout(VitalSignsPage);
        VitalSignsPage.setLayout(VitalSignsPageLayout);
        VitalSignsPageLayout.setHorizontalGroup(
            VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(VitalSignsPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VitalSignsPageLayout.createSequentialGroup()
                        .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(VitalSignsPageLayout.createSequentialGroup()
                                .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(encounterIDVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VitalSignsPageLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(encounterID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(respirationRateIDVitalSignsRecording4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(VitalSignsPageLayout.createSequentialGroup()
                                                .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bloodGroupIDVitalSignsRecording)
                                                    .addComponent(patientAgeVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bloodGroupFieldVitalSignsRecording, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(patientAgeFieldVitalSignsRecording, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(VitalSignsPageLayout.createSequentialGroup()
                                                .addComponent(temperatureVitalSignsRecording3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(temperatureFieldVitalSignsRecording4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(27, 27, 27))
                                    .addGroup(VitalSignsPageLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34))))
                            .addGroup(VitalSignsPageLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ClearVitalSigns)))
                        .addGap(18, 18, 18)
                        .addComponent(AddVitalSignsToEncounter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DoctorHomeBack)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VitalSignsPageLayout.createSequentialGroup()
                        .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VitalSignsPageLayout.createSequentialGroup()
                                .addComponent(bloodPressureIDVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bloodPressureFieldVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VitalSignsPageLayout.createSequentialGroup()
                                .addComponent(heightVitalSignsRecording1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(heightFieldVitalSignsRecording1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(respirationRateFieldVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(262, 262, 262))
                    .addGroup(VitalSignsPageLayout.createSequentialGroup()
                        .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VitalSignsPageLayout.createSequentialGroup()
                                .addComponent(diagnosisVitalSignsRecording1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VitalSignsPageLayout.createSequentialGroup()
                                .addComponent(ailmentVitalSignsRecording2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        VitalSignsPageLayout.setVerticalGroup(
            VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VitalSignsPageLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientAgeFieldVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientAgeVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encounterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encounterIDVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodGroupIDVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodGroupFieldVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temperatureVitalSignsRecording3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(heightVitalSignsRecording1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(heightFieldVitalSignsRecording1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(temperatureFieldVitalSignsRecording4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodPressureIDVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respirationRateIDVitalSignsRecording4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodPressureFieldVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respirationRateFieldVitalSignsRecording, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ailmentVitalSignsRecording2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diagnosisVitalSignsRecording1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(VitalSignsPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorHomeBack)
                    .addComponent(AddVitalSignsToEncounter)
                    .addComponent(ClearVitalSigns))
                .addGap(37, 37, 37))
        );

        RightComponent.add(VitalSignsPage, "card7");

        jSplitPane1.setRightComponent(RightComponent);

        javax.swing.GroupLayout WorkspaceLayout = new javax.swing.GroupLayout(Workspace);
        Workspace.setLayout(WorkspaceLayout);
        WorkspaceLayout.setHorizontalGroup(
            WorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        WorkspaceLayout.setVerticalGroup(
            WorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        Parent.add(Workspace, "card5");

        MailIDGrievencesLabel.setText("Mail ID:");

        NumberGrievencesLabel.setText("Number:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        CancelGrievences.setText("Cancel");
        CancelGrievences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelGrievencesActionPerformed(evt);
            }
        });

        SubmitGrievences.setText("Submit");

        javax.swing.GroupLayout GrievencesLayout = new javax.swing.GroupLayout(Grievences);
        Grievences.setLayout(GrievencesLayout);
        GrievencesLayout.setHorizontalGroup(
            GrievencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GrievencesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CancelGrievences)
                .addGap(18, 18, 18)
                .addComponent(SubmitGrievences)
                .addGap(100, 100, 100))
            .addGroup(GrievencesLayout.createSequentialGroup()
                .addGroup(GrievencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GrievencesLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(GrievencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NumberGrievencesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MailIDGrievencesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(GrievencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mailIDGrievences, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberGrievences, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(GrievencesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        GrievencesLayout.setVerticalGroup(
            GrievencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrievencesLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(GrievencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailIDGrievences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MailIDGrievencesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GrievencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberGrievencesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberGrievences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(GrievencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelGrievences)
                    .addComponent(SubmitGrievences))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        Parent.add(Grievences, "card5");

        getContentPane().add(Parent, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rolesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolesComboBoxActionPerformed
        if (rolesComboBox.getSelectedIndex() == 1){
            medicalLicenseNumberTextField.setEnabled(true);
        }else{
            medicalLicenseNumberTextField.setEnabled(false);
        }
    }//GEN-LAST:event_rolesComboBoxActionPerformed

    public String encIDGen(){
        Random ran = new Random();
        int idInt = ran.nextInt(100);
        String encID = "ENC-"+idInt;
        return encID;
    }
    
    public String patIDGen(){
        Random ran = new Random();
        int idInt = ran.nextInt(100);
        String encID = "PAT-"+idInt;
        return encID;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PanelPaint(Register);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PanelPaint(Login);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        
        if (rolesComboBox.getSelectedItem().toString().equals("Doctor")){
            DoctorPerson doc = docDir.addDcotorPerson();
            doc.setUsername(usernameTextField1.getText());
            doc.setPassword(String.valueOf(passwordTextField1.getPassword()));
            doc.setMail(mailIDTextField.getText());
            doc.setRole(rolesComboBox.getSelectedItem().toString());
            doc.setDateOfBirth(jDateChooser1.getDate());
            doc.setPhone(Integer.parseInt(phoneTextField.getText()));
            doc.setMdeicalLicenseNumber(medicalLicenseNumberTextField.getText());
            System.out.println(docDir.getDoctorDir().size());
            PatientAppointmentDrList.addItem(doc.getUsername());
        }else{
            Person person = dir.addPerson();
            person.setUsername(usernameTextField1.getText());
            person.setPassword(String.valueOf(passwordTextField1.getPassword()));
            person.setMail(mailIDTextField.getText());
            person.setRole(rolesComboBox.getSelectedItem().toString());
            person.setDateOfBirth(jDateChooser1.getDate());
            person.setPhone(Integer.parseInt(phoneTextField.getText()));
            person.setUniqueIDPatient(patIDGen());
        }

        PanelPaint(Login);
    }//GEN-LAST:event_registerActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        genderString = "Male";
    }//GEN-LAST:event_maleButtonActionPerformed

    private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
        genderString = "Female";
    }//GEN-LAST:event_femaleButtonActionPerformed

    private void othersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersButtonActionPerformed
        genderString = "Others";
    }//GEN-LAST:event_othersButtonActionPerformed

    private void phoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextFieldActionPerformed
        
    }//GEN-LAST:event_phoneTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Person data = ValidationPerson();
        DoctorPerson dataDoc = ValidationDoctor();
        if (data != null || dataDoc != null){
            if (data.getRole() == "Patient"){
                PanelPaint(Workspace);
                SplitPanelPaint(PatientHome);
                
            }else if(dataDoc.getRole() == "Doctor"){
                PanelPaint(Workspace);
                SplitPanelPaint(DoctorHome);
                doctorAppointmentsList(dataDoc.getUsername());
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid username and password.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void doctorAppointmentsList(String name){
        DefaultTableModel doctorTable = (DefaultTableModel)DoctorAppointment.getModel();
        doctorTable.setRowCount(0);
        for (Encounter enc : encHistory.getEncounterHistory()){
            if(enc.getEncounterWith().equals(name)){
                String docTableIn[] = {enc.getEncounterID(), enc.getUsername(), enc.getEncounterDate(), enc.getAilment()};                
                doctorTable.addRow(docTableIn);
            }
        }
    }
    
    public void patientAppointmentsList(String name){
        DefaultTableModel patientTable = (DefaultTableModel) PatienAppointmentHistory.getModel();
        patientTable.setRowCount(0);
        for (Encounter enc : encHistory.getEncounterHistory()){
            if (enc.getUsername().equals(name)){
                String dataIn[] = {enc.getEncounterWith(), enc.getEncounterDate(), enc.getAilment()};
                patientTable.addRow(dataIn);
            }
        }
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PanelPaint(Grievences);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        PanelPaint(Login);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CancelGrievencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelGrievencesActionPerformed
        PanelPaint(Login);
    }//GEN-LAST:event_CancelGrievencesActionPerformed

    private void createAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAppointmentActionPerformed
        SplitPanelPaint(CreatePatientAppointment);
    }//GEN-LAST:event_createAppointmentActionPerformed

    private void PatientAppointmentCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientAppointmentCancelActionPerformed
        SplitPanelPaint(PatientHome);
    }//GEN-LAST:event_PatientAppointmentCancelActionPerformed

    private void PatientAppointmentSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientAppointmentSubmitActionPerformed
        SplitPanelPaint(PatientHome);
        //Here we will add methods to add data to storage.
        Encounter enc = encHistory.addEncounterHistory();
        enc.setUsername(ValidationPerson().getUsername());
        enc.setGender(ValidationPerson().getGender());
        enc.setHeartRate(0);
        enc.setMail(ValidationPerson().getMail());
        enc.setPhone(ValidationPerson().getPhone());
        enc.setRespirationRate(0);
        enc.setBodyTemperatur(0);
        enc.setBloodPressure(0);
        enc.setHeight(0);
        enc.setRole(ValidationPerson().getRole());
        enc.setAilment(jTextArea2.getText());
        enc.setEncounterDate(PatientAppointmentDateChooser.getDate().toString());
        enc.setEncounterWith(PatientAppointmentDrList.getSelectedItem().toString());
        enc.setEncounterID(encIDGen());
        //DefaultTableModel patientTable = (DefaultTableModel) PatienAppointmentHistory.getModel();
        //String dataIn[] = {enc.getEncounterWith(), enc.getEncounterDate(), enc.getAilment()};
        //patientTable.addRow(dataIn);
        
    }//GEN-LAST:event_PatientAppointmentSubmitActionPerformed

    private void BackToPatientHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToPatientHomeActionPerformed
        SplitPanelPaint(PatientHome);
        ViewAppointmentUsername.setText("Username: ");
        ViewAppointmentWith.setText("Appointment with: ");
        ViewAppointmentDate.setText("Appointment date: ");
        HeartRate.setText("Heart rate: ");
    }//GEN-LAST:event_BackToPatientHomeActionPerformed

    private void viewAppoitnmentPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAppoitnmentPatientActionPerformed
        SplitPanelPaint(ViewPatientAppointment);
        DefaultTableModel patientTable = (DefaultTableModel) PatienAppointmentHistory.getModel();
        patientTable.setRowCount(0);
        for (Encounter enc : encHistory.getEncounterHistory()){
            if (enc.getUsername().equals(ValidationPerson().getUsername())){
                String dataIn[] = {enc.getEncounterID(), enc.getEncounterWith(), enc.getEncounterDate(), enc.getAilment()};
                patientTable.addRow(dataIn);
            }
        }
    }//GEN-LAST:event_viewAppoitnmentPatientActionPerformed

    private void ViewEncounterHistoryDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEncounterHistoryDoctorActionPerformed
        SplitPanelPaint(PatientEncounterHistory);//to add some data
    }//GEN-LAST:event_ViewEncounterHistoryDoctorActionPerformed

    private void AddVitalSignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVitalSignsActionPerformed
        SplitPanelPaint(VitalSignsPage);
        //Encounter enc = new Encounter();
        int row = DoctorAppointment.getSelectedRow();
        if (row != -1 ){
            String ID = DoctorAppointment.getValueAt(row, 0).toString();
            for (Encounter e:encHistory.getEncounterHistory()){
                if (e.getEncounterID().equals(ID)){
                    encToWorkWith = e;
                }
            }
            userName.setText(encToWorkWith.getUsername());
            bloodGroupFieldVitalSignsRecording.setText("A+");
            encounterID.setText(encToWorkWith.getEncounterID());
            //need to add age as well
            jTextArea4.setText(encToWorkWith.getAilment());
        }
    }//GEN-LAST:event_AddVitalSignsActionPerformed

    private void DoctorHomeBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorHomeBack1ActionPerformed
        SplitPanelPaint(DoctorHome);
    }//GEN-LAST:event_DoctorHomeBack1ActionPerformed

    private void DoctorHomeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorHomeBackActionPerformed
        SplitPanelPaint(DoctorHome);
    }//GEN-LAST:event_DoctorHomeBackActionPerformed

    private void PatienAppointmentHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatienAppointmentHistoryMouseClicked
        int row = PatienAppointmentHistory.getSelectedRow();
        //Need to use Encounter ID to show the right data population.
        String id = PatienAppointmentHistory.getValueAt(row, 0).toString();
        Encounter enc = encHistory.getEncounterHistory().get(row);
        ViewAppointmentUsername.setText("Username: "+enc.getUsername());
        ViewAppointmentWith.setText("Appointment with: "+enc.getEncounterWith());
        ViewAppointmentDate.setText("Appointment date: "+enc.getEncounterDate());
        HeartRate.setText("Heart rate: "+enc.getHeartRate());
        BloodpressureViewAppointment.setText("Blood Pressure: "+enc.getBloodPressure());
        temperatureViewAppointment.setText("Temperature: "+enc.getBodyTemperatur());
        respirationRateViewAppointment.setText("Respiration Rate: "+enc.getRespirationRate());
        HeightViewAppointment.setText("Height: "+enc.getHeight() + "cm.");
        DiagnosisViewAppointment.setText("Diagnosis: "+enc.getDiagnosis());
        ViewAppointmentAilment.setText("Ailment: "+enc.getAilment()+" "+enc.getRole());
    }//GEN-LAST:event_PatienAppointmentHistoryMouseClicked

    private void AddVitalSignsToEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVitalSignsToEncounterActionPerformed
        //int indexedVal = encHistory.getEncounterHistory().indexOf(encounterID.getText());
        //Encounter enc = encHistory.getEncounterHistory().get(indexedVal);
        System.out.println(encToWorkWith.getEncounterID());
        encToWorkWith.setBloodPressure(Integer.parseInt(bloodPressureFieldVitalSignsRecording.getText()));
        encToWorkWith.setHeight(Integer.parseInt(heightFieldVitalSignsRecording1.getText()));
        encToWorkWith.setBloodPressure(Integer.parseInt(bloodPressureFieldVitalSignsRecording.getText()));
        encToWorkWith.setRespirationRate(Integer.parseInt(respirationRateFieldVitalSignsRecording.getText()));
        encToWorkWith.setDiagnosis(jTextArea3.getText());
    }//GEN-LAST:event_AddVitalSignsToEncounterActionPerformed
    
    public Person ValidationPerson(){
        Person specificP = new Person();
        for (Person p: dir.getDir()){
            if (p.getUsername().equals(usernameTextField.getText()) && p.getPassword().equals(String.valueOf(passwordTextField.getPassword()))){
                System.out.println(p.getUsername());
                specificP = p;
            }
        }return specificP;
    }
    
    public DoctorPerson ValidationDoctor(){
        DoctorPerson doc = new DoctorPerson();
        for (DoctorPerson dr: docDir.getDoctorDir()){
            if (dr.getUsername().equals(usernameTextField.getText()) && dr.getPassword().equals(String.valueOf(passwordTextField.getPassword()))){
                System.out.println(dr.getUsername()+ dr.getRole()+ dr.getMdeicalLicenseNumber());
                doc = dr;
            }
            
    }return doc;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hospitalManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hospitalManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hospitalManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hospitalManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hospitalManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVitalSigns;
    private javax.swing.JButton AddVitalSignsToEncounter;
    private javax.swing.JLabel AppLogo;
    private javax.swing.JLabel AppLogo1;
    private javax.swing.JButton BackToPatientHome;
    private javax.swing.JLabel BloodpressureViewAppointment;
    private javax.swing.JButton CancelGrievences;
    private javax.swing.JButton ClearVitalSigns;
    private javax.swing.JPanel CreatePatientAppointment;
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel DiagnosisViewAppointment;
    private javax.swing.JTable DoctorAppointment;
    private javax.swing.JPanel DoctorHome;
    private javax.swing.JButton DoctorHomeBack;
    private javax.swing.JButton DoctorHomeBack1;
    private javax.swing.JPanel Grievences;
    private javax.swing.JLabel HeartRate;
    private javax.swing.JLabel HeightViewAppointment;
    private javax.swing.JPanel Login;
    private javax.swing.JLabel MailIDGrievencesLabel;
    private javax.swing.JTextField NumberGrievences;
    private javax.swing.JLabel NumberGrievencesLabel;
    private javax.swing.JPanel Parent;
    private javax.swing.JTable PatienAppointmentHistory;
    private javax.swing.JButton PatientAppointmentCancel;
    private javax.swing.JLabel PatientAppointmentDate;
    private com.toedter.calendar.JDateChooser PatientAppointmentDateChooser;
    private javax.swing.JLabel PatientAppointmentDoctor;
    private javax.swing.JComboBox<String> PatientAppointmentDrList;
    private javax.swing.JLabel PatientAppointmentReason;
    private javax.swing.JScrollPane PatientAppointmentReasonArea;
    private javax.swing.JButton PatientAppointmentSubmit;
    private javax.swing.JPanel PatientEncounterHistory;
    private javax.swing.JTable PatientEncounterHistoryDoctor;
    private javax.swing.JPanel PatientHome;
    private javax.swing.JPanel Register;
    private javax.swing.JPanel RightComponent;
    private javax.swing.JButton SubmitGrievences;
    private javax.swing.JLabel ViewAppointmentAilment;
    private javax.swing.JLabel ViewAppointmentDate;
    private javax.swing.JLabel ViewAppointmentUsername;
    private javax.swing.JLabel ViewAppointmentWith;
    private javax.swing.JButton ViewEncounterHistoryDoctor;
    private javax.swing.JPanel ViewPatientAppointment;
    private javax.swing.JPanel VitalSignsPage;
    private javax.swing.JPanel Workspace;
    private javax.swing.JLabel ailmentVitalSignsRecording2;
    private javax.swing.JTextField bloodGroupFieldVitalSignsRecording;
    private javax.swing.JLabel bloodGroupIDVitalSignsRecording;
    private javax.swing.JTextField bloodPressureFieldVitalSignsRecording;
    private javax.swing.JLabel bloodPressureIDVitalSignsRecording;
    private javax.swing.JButton createAppointment;
    private javax.swing.JLabel diagnosisVitalSignsRecording1;
    private javax.swing.JLabel emailID;
    private javax.swing.JTextField encounterID;
    private javax.swing.JLabel encounterIDVitalSignsRecording;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JLabel gender;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JTextField heightFieldVitalSignsRecording1;
    private javax.swing.JLabel heightVitalSignsRecording1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField mailIDGrievences;
    private javax.swing.JTextField mailIDTextField;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JLabel medicalLicense;
    private javax.swing.JTextField medicalLicenseNumberTextField;
    private javax.swing.JRadioButton othersButton;
    private javax.swing.JLabel password;
    private javax.swing.JLabel password1;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPasswordField passwordTextField1;
    private javax.swing.JTextField patientAgeFieldVitalSignsRecording;
    private javax.swing.JLabel patientAgeVitalSignsRecording;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JButton register;
    private javax.swing.JTextField respirationRateFieldVitalSignsRecording;
    private javax.swing.JLabel respirationRateIDVitalSignsRecording4;
    private javax.swing.JLabel respirationRateViewAppointment;
    private javax.swing.JLabel role;
    private javax.swing.JComboBox<String> rolesComboBox;
    private javax.swing.JTextField temperatureFieldVitalSignsRecording4;
    private javax.swing.JLabel temperatureViewAppointment;
    private javax.swing.JLabel temperatureVitalSignsRecording3;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JTextField usernameTextField1;
    private javax.swing.JLabel usernameVitalSignsRecording;
    private javax.swing.JButton viewAppoitnmentPatient;
    // End of variables declaration//GEN-END:variables
}
